"""
Utility functions for NYC Taxi Analytics Dashboard
"""

import pandas as pd
import streamlit as st

def get_nyc_location_name(location_id):
    """Convert NYC taxi zone ID to actual location name"""
    # NYC Taxi Zone mapping (based on NYC TLC data)
    nyc_zones = {
        1: "Newark Airport",
        2: "Jamaica Bay",
        3: "Allerton/Pelham Gardens",
        4: "Alphabet City",
        5: "Arden Heights",
        6: "Arrochar/Fort Wadsworth",
        7: "Astoria",
        8: "Astoria Park",
        9: "Auburndale",
        10: "Baisley Park",
        11: "Bath Beach",
        12: "Battery Park City",
        13: "Bay Ridge",
        14: "Bay Terrace/Fort Totten",
        15: "Bayside",
        16: "Bedford",
        17: "Bedford Park",
        18: "Bellerose",
        19: "Belmont",
        20: "Bensonhurst East",
        21: "Bensonhurst West",
        22: "Bloomfield/Emerson Hill",
        23: "Bluemont Park",
        24: "Boerum Hill",
        25: "Borough Park",
        26: "Breezy Point/Fort Tilden/Riis Beach",
        27: "Briarwood/Jamaica Hills",
        28: "Brighton Beach",
        29: "Bronx Park",
        30: "Brooklyn Heights",
        31: "Brooklyn Navy Yard",
        32: "Brownsville",
        33: "Bushwick North",
        34: "Bushwick South",
        35: "Cambria Heights",
        36: "Canarsie",
        37: "Carroll Gardens",
        38: "Central Harlem",
        39: "Central Harlem North",
        40: "Central Park",
        41: "Charleston/Tottenville",
        42: "Chinatown",
        43: "City Island",
        44: "Claremont/Bathgate",
        45: "Clinton East",
        46: "Clinton Hill",
        47: "Clinton West",
        48: "Co-Op City",
        49: "Cobble Hill",
        50: "College Point",
        51: "Columbia Street",
        52: "Coney Island",
        53: "Corona",
        54: "Corona North",
        55: "Country Club",
        56: "Crown Heights North",
        57: "Crown Heights South",
        58: "Cypress Hills",
        59: "DUMBO/Vinegar Hill",
        60: "Douglas Manor/Douglaston",
        61: "Downtown Brooklyn/MetroTech",
        62: "Downtown Jamaica",
        63: "East Chelsea",
        64: "East Flatbush/Farragut",
        65: "East Harlem North",
        66: "East Harlem South",
        67: "East New York",
        68: "East New York/Pennsylvania Avenue",
        69: "East Tremont",
        70: "East Village",
        71: "East Williamsburg",
        72: "Eastchester",
        73: "Elmhurst",
        74: "Elmhurst/Maspeth",
        75: "Erasmus",
        76: "Far Rockaway",
        77: "Flatbush/Ditmas Park",
        78: "Flatiron",
        79: "Flatlands",
        80: "Flushing",
        81: "Flushing Meadows-Corona Park",
        82: "Fordham South",
        83: "Forest Hills",
        84: "Fort Greene",
        85: "Fresh Meadows",
        86: "Freshkills Park",
        87: "Garment District",
        88: "Glen Oaks",
        89: "Glendale",
        90: "Governors Island/Ellis Island/Liberty Island",
        91: "Gowanus",
        92: "Gramercy",
        93: "Gravesend",
        94: "Great Kills",
        95: "Green-Wood Cemetery",
        96: "Greenpoint",
        97: "Grymes Hill/Clifton",
        98: "Hamilton Heights",
        99: "Hammels/Arverne/Edgemere",
        100: "Highbridge",
        101: "Hollis",
        102: "Homecrest",
        103: "Hudson Yards",
        104: "Hunters Point/Sunnyside West",
        105: "Hunts Point",
        106: "Jackson Heights",
        107: "Jamaica",
        108: "Jamaica Estates/Holliswood",
        109: "JFK Airport",
        110: "Kensington",
        111: "Kew Gardens",
        112: "Kew Gardens Hills",
        113: "Kingsbridge",
        114: "Kingsbridge Heights",
        115: "Kips Bay",
        116: "LaGuardia Airport",
        117: "Laurelton",
        118: "Lenox Hill/Roosevelt Island",
        119: "Lincoln Square East",
        120: "Lincoln Square West",
        121: "Little Italy/NoLiTa",
        122: "Long Island City/Hunters Point",
        123: "Long Island City/Queens Plaza",
        124: "Longwood",
        125: "Lower East Side",
        126: "Madison",
        127: "Manhattan Beach",
        128: "Manhattan Valley",
        129: "Manhattanville",
        130: "Marble Hill",
        131: "Marine Park/Floyd Bennett Field",
        132: "Marine Park/Mill Basin",
        133: "Mariners Harbor",
        134: "Maspeth",
        135: "Meatpacking/West Village West",
        136: "Melrose South",
        137: "Middle Village",
        138: "Midtown Center",
        139: "Midtown East",
        140: "Midtown North",
        141: "Midtown South",
        142: "Midwood",
        143: "Morningside Heights",
        144: "Morrisania/Melrose",
        145: "Mott Haven/Port Morris",
        146: "Mount Hope",
        147: "Murray Hill",
        148: "Murray Hill-Queens",
        149: "New Dorp/Midland Beach",
        150: "North Corona",
        151: "Norwood",
        152: "Oakland Gardens",
        153: "Oakwood",
        154: "Ocean Hill",
        155: "Ocean Parkway South",
        156: "Old Astoria",
        157: "Ozone Park",
        158: "Park Slope",
        159: "Parkchester",
        160: "Pelham Bay",
        161: "Pelham Bay Park",
        162: "Pelham Parkway",
        163: "Penn Station/Madison Sq West",
        164: "Port Richmond",
        165: "Prospect-Lefferts Gardens",
        166: "Prospect Heights",
        167: "Prospect Park",
        168: "Queens Village",
        169: "Queensboro Hill",
        170: "Queensbridge/Ravenswood",
        171: "Randalls Island",
        172: "Red Hook",
        173: "Rego Park",
        174: "Richmond Hill",
        175: "Ridgewood",
        176: "Rikers Island",
        177: "Riverdale/North Riverdale/Fieldston",
        178: "Rockaway Park",
        179: "Roosevelt Island",
        180: "Rosedale",
        181: "Rossville/Woodrow",
        182: "Saint Albans",
        183: "Saint George/New Brighton",
        184: "Saint Michaels Cemetery/Woodside",
        185: "Schuylerville/Edgewater Park",
        186: "Seaport",
        187: "Sheepshead Bay",
        188: "SoHo",
        189: "Soundview/Bruckner",
        190: "Soundview/Castle Hill",
        191: "South Beach/Dongan Hills",
        192: "South Jamaica",
        193: "South Ozone Park",
        194: "South Williamsburg",
        195: "Springfield Gardens North",
        196: "Springfield Gardens South",
        197: "Spuyten Duyvil/Kingsbridge",
        198: "Stapleton",
        199: "Starrett City",
        200: "Steinway",
        201: "Stuy Town/Peter Cooper Village",
        202: "Stuyvesant Heights",
        203: "Sunnyside",
        204: "Sunset Park East",
        205: "Sunset Park West",
        206: "Sutton Place/Turtle Bay North",
        207: "Times Sq/Theatre District",
        208: "TriBeCa/Civic Center",
        209: "Two Bridges/Seward Park",
        210: "UN/Turtle Bay South",
        211: "Union Sq",
        212: "University Heights/Morris Heights",
        213: "Upper East Side North",
        214: "Upper East Side South",
        215: "Upper West Side North",
        216: "Upper West Side South",
        217: "Van Cortlandt Park",
        218: "Van Cortlandt Village",
        219: "Van Nest/Morris Park",
        220: "Washington Heights North",
        221: "Washington Heights South",
        222: "West Brighton",
        223: "West Chelsea/Hudson Yards",
        224: "West Concourse",
        225: "West Farms/Bronx River",
        226: "West Village",
        227: "Westchester Village/Unionport",
        228: "Westerleigh",
        229: "Whitestone",
        230: "Williamsbridge/Olinville",
        231: "Williamsburg",
        232: "Williamsburg North",
        233: "Willowbrook",
        234: "Windsor Terrace",
        235: "Woodhaven",
        236: "Woodlawn/Wakefield",
        237: "Woodside",
        238: "World Trade Center",
        239: "Yorkville East",
        240: "Yorkville West",
        241: "park-cemetery-etc",
        242: "undefined",
        243: "Jamaica Bay",
        244: "Nassau or Westchester",
        245: "NA",
        246: "JFK Airport",
        247: "LaGuardia Airport",
        248: "Manhattan",
        249: "Queens",
        250: "Staten Island",
        251: "Bronx",
        252: "EWR",
        253: "LGA",
        254: "JFK",
        255: "Downtown Brooklyn/MetroTech",
        256: "Brooklyn",
        257: "Queens",
        258: "Bronx",
        259: "Staten Island",
        260: "Manhattan",
        261: "Airport",
        262: "Battery Park",
        263: "Central Park"
    }
    
    return nyc_zones.get(location_id, f"Zone {location_id}")

def create_enhanced_metrics(df):
    """Create enhanced summary metrics with better styling"""
    if df.empty:
        return
    
    col1, col2, col3, col4 = st.columns(4)
    
    with col1:
        st.markdown(f"""
        <div class="metric-card">
            <div class="metric-value">{len(df):,}</div>
            <div class="metric-label">Total Trips</div>
        </div>
        """, unsafe_allow_html=True)
    
    with col2:
        avg_fare = df['fare_amount'].mean()
        st.markdown(f"""
        <div class="metric-card">
            <div class="metric-value">${avg_fare:.2f}</div>
            <div class="metric-label">Average Fare</div>
        </div>
        """, unsafe_allow_html=True)
    
    with col3:
        total_revenue = df['total_amount'].sum()
        st.markdown(f"""
        <div class="metric-card">
            <div class="metric-value">${total_revenue:,.0f}</div>
            <div class="metric-label">Total Revenue</div>
        </div>
        """, unsafe_allow_html=True)
    
    with col4:
        avg_tip_pct = df['tip_percentage'].mean()
        st.markdown(f"""
        <div class="metric-card">
            <div class="metric-value">{avg_tip_pct:.1f}%</div>
            <div class="metric-label">Average Tip %</div>
        </div>
        """, unsafe_allow_html=True) 